错误和异常的处理是程序中很重要的一部分。下面介绍几种常用异常和错误处理方式：

## 返回错误编号

我们可以让方法使用不同的编号来表示不同含义，如下：

```c#
namespace CleanCSharp.Errors.Dirty
{
    public class SomeClass
    {
        public int DoSomeProcess(int? id)
        {
            if (id == null)
            {
                // null id 
                return -1;
            }
            string data = LoadData();
            if (string.IsNullOrWhiteSpace(data))
            {
                // data is corrupt 
                return -2;
            }
            ProcessData(data);
            // no error, all good
            return 0;
        }
        
        private string LoadData()
        {
            return "some data";
        }
        
        private void ProcessData(string data)
        {
            // do something 
        }
    }
}
```

上述代码中`DoSomeProcess`方法的返回值均是魔法值，建议改为常量。客户端再调用`DoSomeProcess`方法时需要针对不同的返回值分别处理：

```c#
namespace CleanCSharp.Errors.Dirty
{
    public class ConsumerOfSomeClass
    {
        public void Consume()
        {
            var sc = new SomeClass();
            const int idToProcess = 42;
            int returnCode = sc.DoSomeProcess(idToProcess);
            switch (returnCode)
            {
                case -1: // null id 
                    // do something
                    break;
                case -2: // corrupt data 
                    // do something 
                    break;
                case 0: // no error 
                    Save(idToProcess);
                    break;
            }
        }

        private void Save(int id)
        {
            // save 
        }
    }
}
```

返回错误编号的方式有以下缺点：

1、直接返回数值，语义不清晰，调用者不晓得1或-1表示的什么意思，可读性差不利于维护；

2、每个调用者都需要对各种返回值做处理，比较繁琐，也有可能遗漏；

3、如果`DoSomeProcess`方法中添加了新的返回值，那么所有的调用者均需要对这个新增的返回值做处理；

基于以上原因，我们可以使用异常来替代方法直接返回数值的情况。

## 使用异常

#### 异常替代错误码

```c#
namespace CleanCSharp.Errors.Clean
{
    public class SomeClass
    {
        public void DoSomeProcess(int? id)
        {
            if (id == null)
            {
                throw new ArgumentNullException("id");
            }
            string data = LoadData();
            ProcessData(data);
        }
        
        private string LoadData()
        {
            var demoData = "";
            if (string.IsNullOrWhiteSpace(demoData))
            {
                throw new InvalidDataException("The data stream contains no data.");
            }
            return demoData;
        }
        
        private void ProcessData(string data)
        {
            // do something 
        }
    }
}
```

客户端调用代码如下：

```c#
namespace CleanCSharp.Errors.Clean
{
    public class ConsumerOfSomeClass
    {
        public void Consume()
        {
            var sc = new SomeClass();
            const int idToProcess = 42;
            try
            {
                sc.DoSomeProcess(idToProcess);
            }
            catch (ArgumentNullException ex)
            {
                // null id
                // do something such as logging
                // if cannot respond to this 
                // exception propagate up the call stack 
                throw; // Notice the throw is not: throw ex;
            }
            catch (InvalidDataException ex)
            {
                // bad data
                // do something
                throw;
            }
            catch (Exception ex)
            {
                // any other exceptions that may occur
                // do something
                throw;
            }
            Save(idToProcess);
        }
        
        private void Save(int id)
        {
            // save 
        }
    }
}
```

#### throw ex & throw & throw new Exception("",ex)

在.NET中:

+ throw ex  

  会重置异常堆栈，只展示ex的堆栈信息；

+ throw        

  会返回从最初引发异常位置处的堆栈信息（即，原始堆栈），信息量比throw ex要大;

+ throw new Exception("message",ex) 

  返回原始堆栈信息及自定义的额外描述信息

#### 注意事项

+ 不要将异常作为返回值或out参数值
+ 异常应作为代码规范的一部分，异常类型不应因为代码版本的迭代而改变
+ 不要使用异常替代普通的流程控制
+ 可以使用帮助类来抛出异常以避免代码重复
+ 抛出的异常信息应能帮助快速定位问题（可作为说明文档来看）且不要包含敏感信息
+ 抛出具有特定含义的异常，而不是通用的异常，如：Exception
+ 过于频繁的抛出异常会影响应用性能

#### 框架内置异常

参考微软文档：[Using Standard Exception Types](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/using-standard-exception-types)

#### 自定义异常

参考微软文档：

[How to create user-defined exceptions](https://docs.microsoft.com/en-us/dotnet/standard/exceptions/how-to-create-user-defined-exceptions)

[Defining Exception Classes](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/exceptions/creating-and-throwing-exceptions#defining-exception-classes)

## 错误编号，异常与返回Null的替代方案

#### Try Method

这部分可参考.NET基础类库中的TryParse方法，如：`int.TryParse("26", out var result);`

```c#
public struct Int32
{
    public static bool TryParse(string s, out int result)
    {
        // ...
    }
}
```

#### 针对特殊情况的设计

下面这段代码用于给客户发邮件，但存在有可能查不到客户信息的情况。在调用`SendEmail`方法前需要判断是否查询到了客户信息：

```c#
namespace CleanCSharp.Errors.Dirty
{
    public class Customer
    {
        public string EmailAddress { get; set; }
        public void SendEmail(string message)
        {
            // send email to customer 
        }
    }
    
    public static class CustomerFinder
    {
        public static Customer Find(int id)
        {
            // if cannot find customer return null;
        }
    }
    
    public class CustomerFinderConsumer
    {
        public void EmailCustomer()
        {
            Customer c = CustomerFinder.Find(42);
            // consumer has to check for nulls 
            if (c != null)
            {
                c.SendEmail("Hello!");
            }
        }
    }
}
```

上述代码可以很好的实现功能，但并不是最优的设计，重构如下：

```c#
namespace CleanCSharp.Errors.Clean
{
    public class Customer
    {
        public string EmailAddress { get; set; }
        public virtual void SendEmail(string message)
        {
            // send email to customer 
        }
    }
    
    public class CustomerNotFound : Customer
    {
        public override void SendEmail(string message)
        {
            // DO NOTHING 
        }
    }
    
    public static class CustomerFinder
    {
        public static Customer Find(int id)
        {
            // if cannot find customer 
            return new CustomerNotFound();
        }
    }
    
    public class CustomerFinderConsumer
    {
        public void EmailCustomer()
        {
            Customer c = CustomerFinder.Find(42);
            c.SendEmail("Hello!");
        }
    }
}
```

重构之后，新增了`CustomerNotFound`类用于处理查询不到客户信息的情况，这样对于API调用方来说无需判断客户信息是否为Null，调用方的处理逻辑也就相对简单了。

## 小结

在我接手的一个项目中，在做参数校验是对于不符合约束的参数一律使用异常进行处理，个人认为这是不合理的。异常应该用来应对可能引发错误的场景中，对于一般流程不应使用异常进行控制。

异常应该在语义上是清晰的，抛异常时不要使用Exception，而是根据具体业务场景来抛出具有特定含义的异常，必要时使用自定义异常。

## 推荐阅读

[Best practices for exceptions](https://docs.microsoft.com/en-us/dotnet/standard/exceptions/best-practices-for-exceptions)

[Exception Throwing](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/exception-throwing)

[Creating and Throwing Exceptions (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/exceptions/creating-and-throwing-exceptions)

[throw and throws in Java](https://www.geeksforgeeks.org/throw-throws-java/)

